export enum PRIVATE_METHOD {
    Balance = "Balance",
    BalanceEx = "BalanceEx",
    TradeBalance = "TradeBalance",
    OpenOrders = "OpenOrders",
    ClosedOrders = "ClosedOrders",
    QueryOrders = "QueryOrders",
    TradesHistory = "TradesHistory",
    QueryTrades = "QueryTrades",
    OpenPositions = "OpenPositions",
    Ledgers = "Ledgers",
    QueryLedgers = "QueryLedgers",
    TradeVolume = "TradeVolume",
    AddExport = "AddExport",
    ExportStatus = "ExportStatus",
    RetrieveExport = "RetrieveExport",
    RemoveExport = "RemoveExport",
    GetWebSocketsToken = "GetWebSocketsToken",
    AddOrder = "AddOrder",
    AddOrderBatch = "AddOrderBatch",
    EditOrder = "EditOrder",
    CancelOrder = "CancelOrder",
    CancelAll = "CancelAll",
    CancelAllOrdersAfter = "CancelAllOrdersAfter",
    DepositMethods = "DepositMethods",
    DepositAddresses = "DepositAddresses",
    DepositStatus = "DepositStatus",
    WithdrawInfo = "WithdrawInfo",
    Withdraw = "Withdraw",
    WithdrawStatus = "WithdrawStatus",
    WithdrawCancel = "WithdrawCancel",
    WalletTransfer = "WalletTransfer",
    StakingAsset= "Staking/Assets",
    Stake = "Stake",
    Unstake = "Unstake",
    StakingPending = "Staking/Pending",
    StakingTransactions = "Staking/Transactions"
}

export enum PUBLIC_METHOD {
    Time = "Time",
    Assets = "Assets",
    AssetPairs = "AssetPairs",
    Ticker = "Ticker",
    OHLC = "OHLC",
    Depth = "Depth",
    Trades = "Trades",
    Spread = "Spread",
    SystemStatus = "SystemStatus"
}